@startuml

start
partition UC1 Просмотр товаров {
    :(Предусловие)
     Просмотр товаров;
 }
partition UC2.1 Добавление товара в корзину {
    :(1) Добавление товара в корзину;
    :(2) Переход в корзину;
 }

partition UC2.2 Действия\nс параметрами\nсписка товаров {
    fork
        :(3) Просмотр добавленных товаров;
    fork again
        :(4) Изменение количества товаров;
    fork again
        :(5) Удаление товара;
    fork again
        :(6) Выбор всех товаров;
     end fork
 }
partition UC2 {
    :(7) Проверка итоговой суммы;
    :(8) Оформление заказа; 
 }
partition UC2.3 {
    :(9) UC2.3 Ввод и проверка данных клиента;
 }
partition UC2.4 {
    :(10)  Оплата заказа;
    :(11) Подтверждение оформления заказа;
 }
partition UC2.5 {
    :(12) UC2.5 Заказ передается курьеру для доставки;
    :(Завершение) 
     Заказ передается курьеру для доставки;
 }

stop
@enduml